### ISSUE TITLE
Implement releases using Docker

### ISSUE THREAD

**Issue by andreskytt** [e-gov/fox#33]
Implement a release process that results in a bunch of docker containers encapsulating the following parts of the system:
- load balancer
- Static web
- FoxAPI
- LoginAPI
- Mock LDAP

**Comment by peterjasc** [comment]
Need to access config/ folder inside the Dockerfile that is in static/ folder.

> The host directory is, by its nature, host-dependent. For this reason, you can’t mount a host directory from Dockerfile because built images should be portable. A host directory wouldn’t be available on all potential hosts. 

(ie, VOLUME ~/git/fox/:/containerdir/ is illegal)

For security reasons, you can not do ADD ../aa /static either (add parent directories -- since they are outside of the build context)

**Comment by peterjasc** [comment]
One possible solution was **(which necessitates .dockerignore in /fox)** this: https://github.com/docker/docker/issues/2745

> I successfully worked around this issue using volumes. Example directory structure:
> 
> web/
> - Dockerfile -> `ADD . /usr/src/app/`
> - (code)
> 
> webstatic/
> - Dockerfile -> `ADD . /usr/src/app/subdir`
> - (code)
> 
> compose file excerpt:
> 
> web:
>   build: ./web/
> 
> webstatic:
>   build: ./webstatic/
>   volumes_from:
>     - web
> 
> Then in the webstatic code I can access the code from the web container. No need for ADD ../web/ .. in webstatic.

**Comment by peterjasc** [comment]
This is not the best solution, since it uses data only containers (Docker Compose file ver 2 seems to have deprecated these with named volumes). A better idea seems to give the dockerfile (in static/) the project's root as the build context (so it could access both static/ and config/).

The implementation of this concept can be seen at https://github.com/e-gov/fox/commit/4528de30666c7ca87778529aad4bf3953ccc72d2

**Comment by peterjasc** [comment]
Links and "expose" (similar to "ports" command, but does not publish ports to host machine) can be considered deprecated features since Docker 1.9 (and should not be used, when writing Docker Compose files of ver 2). Networks should be used instead.

However:

> The default docker0 bridge network supports the use of port mapping and docker run --link to allow communications between containers in the docker0 network. These techniques are cumbersome to set up and prone to error. While they are still available to you as techniques, it is better to avoid them and **define your own bridge networks instead**.

Implementation of user-defined bridge networks and loadbalancers:
https://github.com/e-gov/fox/commit/f0feb24c9eebb04ce4847021e6348608be577aad
Loadbalancer configs:
https://github.com/e-gov/fox/commit/895f2396f0188858f3ec86b255de5880e9b56c6d

https://docs.docker.com/engine/userguide/networking/dockernetworks/
https://docs.docker.com/compose/compose-file/#/expose

**Comment by peterjasc** [comment]
Building go files inside a Docker container with `go build` means that GOPATH needs to point to the project root. This caused some problems in figuring out how to get the build to use a local package's external dependencies located in out project (for example, local pkg "loginservice" is dependant on the following external dependencies located in out project -- "authn", "authz", "login" and "util"), without copying the whole project into every container. 

The solution is quite simple: we just build a similar directory structure inside the container and only copy the files we need, with a small caveat -- we will use the vendor directory for local pkg's local dependencies.

> Go 1.6 includes support for using local copies of external dependencies to satisfy imports of those dependencies, often referred to as vendoring. 

For example, to build Loginservice, we copy authn, authz and util into the vendor folder, instead of directly into the source directory (a small difference, but it makes it clear that these are the external dependencies of pkg login).

```
├── src
...
    ├── login
        └── vendor
        │ └── authn
        │ └── authz
        │ └── util
        └── loginservice
```

**As of July 2016, the "dependency management"/"go vendoring" tools are not mature enough for use in production**, so, in order to  get all the dependencies required for a build, we will have to copy these manually from the host's (from the point of view of the Docker container) source directory into the container's vendor directory and use **`go get -d` to get the other external dependencies (such as github.com/fernet/fernet-go).**

---

For reference:
https://golang.org/cmd/go/#hdr-Vendor_Directories

**Comment by peeterkk** [comment]
> Step 4 : RUN cp /statc/properties.json.sample properties.json 	&& apt-get update 	&& **apt-get install rubygems-integration** 	&& gem update --system 	&& gem install compass --version 1.0.3 	&& npm install && npm install -g grunt-cli
>  ---> Running in 741c31675d5a
> Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
> Get:2 http://security.debian.org jessie/updates/main amd64 Packages [371 kB]
> Ign http://httpredir.debian.org jessie InRelease
> Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
> Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
> Get:5 http://httpredir.debian.org jessie Release [148 kB]
> Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
> Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
> Fetched 9776 kB in 6s (1505 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Suggested packages:
>   bundler
> The following NEW packages will be installed:
>   rubygems-integration
> 0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
> Need to get 4514 B of archives.
> After this operation, 7168 B of additional disk space will be used.
> Get:1 http://httpredir.debian.org/debian/ jessie/main rubygems-integration all 1.8 [4514 B]
> **debconf: delaying package configuration, since apt-utils is not installed**
> Fetched 4514 B in 0s (8580 B/s)
> Selecting previously unselected package rubygems-integration.
> (Reading database ... 21091 files and directories currently installed.)
> Preparing to unpack .../rubygems-integration_1.8_all.deb ...
> Unpacking rubygems-integration (1.8) ...
> Setting up rubygems-integration (1.8) ...
> **/bin/sh: 1: gem: not found**
> The command '/bin/sh -c cp /statc/properties.json.sample properties.json 	&& apt-get update 	&& apt-get install rubygems-integration 	&& gem update --system 	&& gem install compass --version 1.0.3 	&& npm install && npm install -g grunt-cli' returned a non-zero

https://github.com/docker/docker/issues/18180#issuecomment-187583209

**Comment by peterjasc** [comment]
Make static dockerfile buildable  https://github.com/e-gov/fox/commit/1cdede4681ee552cbfeddfa4f76d9d960d4b3479

Remove volume, since it hides the actual folder from Docker container https://github.com/e-gov/fox/commit/993532aced77342fe3ec31d5440904c8ea1de2b2

Replace compass with libsass to not have to get ruby in container 
https://github.com/e-gov/fox/commit/fad0c7bc0d4635ad242d5741276e032905a7159e

 Copy properties into the right directory and update node dependencies 
https://github.com/e-gov/fox/commit/3cb8c734d04d0ca2513833b3a6c98ba11140a962

**Comment by peterjasc** [comment]
For **haproxy logging**, we used rsyslog and mounted /dev/log on the haproxy containers, which means we can read the log at /var/log/syslog

References:
https://github.com/dockerfile/haproxy/issues/3#issuecomment-229586560
https://youroldmanspath.blogspot.com.ee/2015/12/logging-and-haproxy-docker-container.html

**Comment by peterjasc** [comment]
Create a network so that static_web proxies go through load balancers
(Previously, static_web used Fox Service and Login Service directly.)
https://github.com/e-gov/fox/commit/7351e93cd99b5e2d6632e688887484f0a6790257

**Comment by peterjasc** [comment]
set the correct status check address for balancers https://github.com/e-gov/fox/commit/34685838deaaed74392006cb805a3cf480d38d06
